[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/__/auth/*"
  to = "https://flash-pay-937d7.firebaseapp.com/__/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
