name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # Build Client App
      - name: Install Client Dependencies
        run: npm install

      - name: Build Client App
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_ONESIGNAL_APP_ID: "3b38ca69-e5eb-40a7-8b46-48942086dcb3"
          VITE_ADMIN_ONESIGNAL_APP_ID: "987f03ae-6b3f-49ca-9fd4-da1d6323d31e"

      # Build Admin App
      - name: Install Admin Dependencies
        working-directory: "Flash Pay admin"
        run: npm install

      - name: Build Admin App
        working-directory: "Flash Pay admin"
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_ONESIGNAL_APP_ID: "3b38ca69-e5eb-40a7-8b46-48942086dcb3"
          VITE_ONESIGNAL_REST_API_KEY: ${{ secrets.VITE_ONESIGNAL_REST_API_KEY }}

      # Prepare Deployment Folder
      - name: Prepare Deployment
        run: |
          mkdir -p deployment
          cp -r dist/* deployment/
          mkdir -p deployment/admin
          cp -r "Flash Pay admin/dist/"* deployment/admin/
          touch deployment/.nojekyll
          cp deployment/index.html deployment/404.html
          cp deployment/admin/index.html deployment/admin/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deployment
          branch: gh-pages
